# Gopkg.toml for github.com/ulule/loukoum

ignored = [
  "github.com/stretchr/testify/require",
  "github.com/davecgh/go-spew",
  "github.com/lib/pq"
]

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "v1"
  name = "github.com/Masterminds/squirrel"

[[constraint]]
  branch = "master"
  name = "github.com/minodisk/sqlabble"

[[constraint]]
  name = "github.com/doug-martin/goqu"
  version = "4.1.0"
